name: React/Next 自动部署到阿里云

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # 🔥 这是最稳的部署方式，永远不会报密钥错
      - name: Deploy to Aliyun
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          source: ".next/"  # 如果你是 Next.js 改成 .next/
          target: "/home/react-deploy"